spring:
  servlet:
    multipart:
      max-file-size: 5GB # 单个文件最大限制
      max-request-size: 5GB # 请求总大小限制
  data:
    redis:
      database: 2
      host: localhost
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
    mongodb:
      uri: mongodb://localhost:27017/rbac
      auto-index-creation: true
      password: skaIO@1599
      username: ska

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: ska-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # jwt秘钥
  jwt-secret-key: h!a~oAWDAW&*^@AFWE#!o2134SA211+_+WQ_5+_9
  #关闭cookie
  is-read-cookie: false
  # 关闭字符画
  is-print: false

#RES加密
res-key: 1234567890abcdef
